export const transactions = [
    {
        symbol: 'ALV-GY',
        name: 'Allianz SE - Registered shares',
        type: 'Buy',
        date: '2020-01-06',
        shares: 170,
        price: 167,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'AXA-GY',
        name: 'AXA SA',
        type: 'Buy',
        date: '2020-08-31',
        shares: 1150,
        price: 17.14,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BAS-GY',
        name: 'Basf SE',
        type: 'Buy',
        date: '',
        shares: 1090,
        price: 62.48,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BAYN-GY',
        name: 'Bayer AG - Registered shares',
        type: 'Buy',
        date: '',
        shares: 400,
        price: 57.41,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BEI-GY',
        name: 'Beiersdorf AG',
        type: 'Buy',
        date: '',
        shares: 570,
        price: 86,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'DAI-GY',
        name: 'Daimler AG',
        type: 'Buy',
        date: '',
        shares: 1200,
        price: 39.66,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'ECV-GY',
        name: 'Encavis AG',
        type: 'Buy',
        date: '',
        shares: 12,
        price: 0,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'FRE-GY',
        name: 'Fresenius SE & Co. KGaA',
        type: 'Buy',
        date: '',
        shares: 1200,
        price: 43.67,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'HOT-GY',
        name: 'Hochtief AG',
        type: 'Buy',
        date: '',
        shares: 500,
        price: 98.89,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'LHA-GY',
        name: 'Deutsche Lufthansa AG',
        type: 'Buy',
        date: '',
        shares: 4500,
        price: 15.3,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'SAP-GY',
        name: 'Sap SE',
        type: 'Buy',
        date: '',
        shares: 500,
        price: 94.05,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'TLG-GY',
        name: 'TLG Immobilien AG - Bearer shares',
        type: 'Buy',
        date: '',
        shares: 1850,
        price: 23.59,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'TUI1-GY',
        name: 'Tui AG - Registered shares',
        type: 'Buy',
        date: '',
        shares: 5000,
        price: 5.17,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'WDI-GY',
        name: 'Wirecard AG',
        type: 'Buy',
        date: '',
        shares: 300,
        price: 94.36,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'T',
        name: 'AT&T, Inc.',
        type: 'Buy',
        date: '',
        shares: 2700,
        price: 28.97,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BTQ-GM',
        name: 'BT Group',
        type: 'Buy',
        date: '',
        shares: 73000,
        price: 1.48,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'CCC3-GY',
        name: 'Coca-Cola Co',
        type: 'Buy',
        date: '',
        shares: 500,
        price: 48.12,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'GZF-GY',
        name: 'Engie',
        type: 'Buy',
        date: '',
        shares: 1700,
        price: 11.90,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'GSK',
        name: 'Glaxosmithkline plc - ADR',
        type: 'Buy',
        date: '',
        shares: 5000,
        price: 14.79,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'INN1-GY',
        name: 'ING Groep N.V.',
        type: 'Buy',
        date: '',
        shares: 14000,
        price: 8.12,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'INTC',
        name: 'Intel Corp.',
        type: 'Buy',
        date: '',
        shares: 500,
        price: 48.92,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'NOA3-GY',
        name: 'Nokia Corp.',
        type: 'Buy',
        date: '',
        shares: 10000,
        price: 3.43,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'NOTA-GM',
        name: 'Novartis AG - ADR',
        type: 'Buy',
        date: '',
        shares: 300,
        price: 77.33,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'PRG-GY',
        name: 'Procter & Gamble Co.',
        type: 'Buy',
        date: '',
        shares: 600,
        price: 127.07,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: '3RB-GF',
        name: 'Reckitt Benckiser Group Plc',
        type: 'Buy',
        date: '',
        shares: 1100,
        price: 63.18,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'SNW-GY',
        name: 'Sanofi',
        type: 'Buy',
        date: '',
        shares: 900,
        price: 79.69,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'SCTA-GF',
        name: 'SSE Plc. - ADR',
        type: 'Buy',
        date: '',
        shares: 1100,
        price: 14.37,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'TNE5-GY',
        name: 'Telefonica S.A',
        type: 'Buy',
        date: '',
        shares: 6597,
        price: 4.44,
        cashValue: null,
        commission: 0,
        notes: '',
    },

]
export const symbols = [
    'ALV-GY', 'AXA-GY', 'BAS-GY', 'BAYN-GY', 'BEI-GY', 'DAI-GY', 'ECV-GY', 'FRE-GY', 'HOT-GY', 'LHA-GY', 'SAP-GY', 'TLG-GY', 'TUI1-GY', 'WDI-GY', 'T', 'BTQ-GM', 'CCC3-GY', 'GZF-GY', 'GSK', 'INN1-GY', 'INTC', 'NOA3-GY', 'NOTA-GM', 'PRG-GY', '3RB-GF', 'SNW-GY', 'SCTA-GF', 'TNE5-GY'
]