export const transactions = [
    {
        symbol: 'ALV-GY',
        name: 'Allianz SE - Registered shares',
        type: 'Buy',
        date: '2020-01-06',
        shares: 170,
        price: 167,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'AXA-GY',
        name: 'AXA SA',
        type: 'Buy',
        date: '2020-08-31',
        shares: 1150,
        price: 17.14,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BAS-GY',
        name: 'Basf SE',
        type: 'Buy',
        date: '',
        shares: 1090,
        price: 62.48,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BAYN-GY',
        name: 'Bayer AG - Registered shares',
        type: 'Buy',
        date: '',
        shares: 400,
        price: 57.41,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'BEI-GY',
        name: 'Beiersdorf AG',
        type: 'Buy',
        date: '',
        shares: 570,
        price: 86,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'DAI-GY',
        name: 'Daimler AG',
        type: 'Buy',
        date: '',
        shares: 1200,
        price: 39.66,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'ECV-GY',
        name: 'Encavis AG',
        type: 'Buy',
        date: '',
        shares: 12,
        price: 0,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'ECV-GY',
        name: 'Encavis AG',
        type: 'Buy',
        date: '',
        shares: 1100,
        price: 18.22,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'FRE-GY',
        name: 'Fresenius SE & Co. KGaA',
        type: 'Buy',
        date: '',
        shares: 1200,
        price: 43.67,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'HOT-GY',
        name: 'Hochtief AG',
        type: 'Buy',
        date: '',
        shares: 500,
        price: 98.89,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'LHA-GY',
        name: 'Deutsche Lufthansa AG',
        type: 'Buy',
        date: '',
        shares: 4500,
        price: 15.3,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'SAP-GY',
        name: 'Sap SE',
        type: 'Buy',
        date: '',
        shares: 500,
        price: 94.05,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'TLG-GY',
        name: 'TLG Immobilien AG - Bearer shares',
        type: 'Buy',
        date: '',
        shares: 1850,
        price: 23.59,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'TUI1-GY',
        name: 'Tui AG - Registered shares',
        type: 'Buy',
        date: '',
        shares: 5000,
        price: 5.17,
        cashValue: null,
        commission: 0,
        notes: '',
    },
    {
        symbol: 'WDI-GY',
        name: 'Wirecard AG',
        type: 'Buy',
        date: '',
        shares: 300,
        price: 94.36,
        cashValue: null,
        commission: 0,
        notes: '',
    },
]

export const symbols = [
    'ALV-GY', 'AXA-GY', 'BAS-GY', 'BAYN-GY', 'BEI-GY', 'DAI-GY', 'ECV-GY', 'ECV-GY', 'FRE-GY', 'HOT-GY', 'LHA-GY', 'SAP-GY', 'TLG-GY', 'TUI1-GY', 'WDI-GY'
]
